#!/usr/bin/python
import os, sys, subprocess

def realArgs(args):
    oargs = []
    parg = False
    for arg in args:
        if arg == '-l': parg = True
        else: oargs.append(arg)
    return [oargs,parg]
def paint(color,string):
    colors = {
        'pink':'\033[95m',
        'blue':'\033[94m',
        'green':'\033[92m',
        'yellow':'\033[93m',
        'red':'\033[91m',
        'end':'\033[0m',
        'bold':'\033[1m',
        'underline':'\033[4m'
    }
    return(colors[color]+string+colors['end'])

def size_format(s, u='B'):
    unit = ['B','K','M','G','T','P','E']
    for i in range(1,len(unit)):
        if float(s) >= float(1024):
            s = s / 1024
            u = unit[i]
    s = ''.join(['{:.2f}'.format(s),u])
    return s

def get_files_size_in_dir(arg):
    files = []
    for r,d,f in os.walk(arg):
        for a in f:
            files.append(os.path.join(r,a))
    return sum(list(map(lambda a: os.path.getsize(a),files)))

def size(oarg,arg,listing):
    if os.path.isdir(arg):
        print(paint('yellow',size_format(get_files_size_in_dir(arg)))+"\t"+paint('pink',oarg))
        if listing:
            for element in list(map(lambda a: [a,arg+a],os.listdir(arg))):
                if os.path.isdir(element[1]):
                    print("\t"+paint('yellow',size_format(get_files_size_in_dir(element[1])))+"\t"+paint('blue',element[0]+'/'))
                else:
                    print("\t"+paint('yellow',size_format(os.path.getsize(element[1])))+"\t"+paint('green',element[0]))
    else:
        print(size_format(os.path.getsize(arg))+"\t"+paint('green',oarg))

pwd = subprocess.run(['pwd'], stdout=subprocess.PIPE).stdout.decode('utf-8').replace('\n','')
un = subprocess.run(['whoami'], stdout=subprocess.PIPE).stdout.decode('utf-8').replace('\n','')
listing = realArgs(sys.argv[1:])[1]
if len(sys.argv[1:]) <= 1: sys.argv.append(pwd)
args = realArgs(sys.argv[1:])[0]

for arg in args:
    oarg = arg
    arg = os.path.abspath(arg)
    if os.path.exists(arg):
        if os.path.isdir(arg):
            if arg[-1] != '/': arg += '/'
            if oarg[-1] != '/': oarg += '/'
        size(oarg, arg,listing)
    else:
        print(paint('red',"Doesn't Exist ! ==> {}".format(oarg)))
